### ISSUE TITLE
check conversion bit

### ISSUE THREAD

**Issue by Rujo** [rpsreal/fast_read_ADS1015#1]
The while loop checking the conversion bit (15) is wrong.

it is: 
 while ((readi2c(i2caddress, 0x01) & 0x80) == 0);  // Espera que o config register OS bit mude para 1 (conversão concluida) 

It should be: (bit 15)
 while ((readi2c(i2caddress, 0x01) & 0x8000) == 0);  // Espera que o config register OS bit mude para 1 (conversão concluida)

**Comment by rpsreal** [comment]
Thank you, it's already fixed.
